Repository KunjShah95/UPI-FRAUD-DETECTION-SYSTEM, pull requests merged in 2025-06, with the labels that each got.

#1 Update README.md
  README.md
Labels: Review effort 1/5

#2 Fix: Resolve major issues in UPI Fraud Detection System
  CHANGELOG.md
  Data_Analysis_for_UPI_Payment_Systems (1).ipynb
  Data_Analysis_for_UPI_Payment_Systems_Fixed.ipynb
  README.md
  requirements.txt
Labels: Review effort 4/5

#3 Create main.py
  webapp/main.py
Labels: Review effort 3/5
